import os
import json
import re
import requests
from typing import Dict, Optional, List
from datetime import datetime, timedelta

# 预编译正则表达式，避免每次调用时重新编译
_RE_PARENS = re.compile(r'\s*\([^)]*\)')
_RE_BRACKETS = re.compile(r'\s*\[[^\]]*\]')
_RE_TRAILING_COLON = re.compile(r'\s*:\s*$')

class ImpactFactorFetcher:
    """影响因子查询器"""
    
    def __init__(self, cache_file: str = 'impact_factor_cache.json'):
        self.cache_file = cache_file
        self.cache = self._load_cache()
        
        # 常见期刊的影响因子（作为后备）
        self.common_journals = {
            'nature': 64.8,
            'cell': 64.5,
            'science': 56.9,
            'science advances': 13.6,
            'advanced science': 16.7,
            'nature reviews drug discovery': 120.1,
            'nature reviews molecular cell biology': 112.7,
            'nature reviews cancer': 78.5,
            'nature medicine': 82.9,
            'nature biotechnology': 46.9,
            'nature cell biology': 21.3,
            'nature communications': 16.6,
            'cell research': 44.1,
            'molecular cell': 17.0,
            'cancer cell': 50.3,
            'cell chemical biology': 8.6,
            'cell discovery': 33.5,
            'journal of medicinal chemistry': 7.3,
            'acs chemical biology': 4.0,
            'chemical science': 8.4,
            'angewandte chemie': 16.6,
            'journal of the american chemical society': 15.0,
            'acs central science': 18.7,
            'chemistry \u0026 biology': 6.6,
            'chembiochem': 3.2,
            'bioorganic \u0026 medicinal chemistry': 3.5,
            'european journal of medicinal chemistry': 6.7,
            'journal of biological chemistry': 4.8,
            'cell death \u0026 differentiation': 12.4,
            'oncogene': 8.0,
            'cancer research': 12.5,
            'clinical cancer research': 13.8,
            'cancer letters': 9.7,
            'journal of hematology \u0026 oncology': 28.5,
            'leukemia': 11.4,
            'blood': 21.0,
            'biorxiv': 0.0,
            'medrxiv': 0.0,
            'arxiv': 0.0,
            'proceedings of the national academy of sciences': 11.1,
            'pnas': 11.1,
            'elife': 7.7,
            'plos biology': 9.8,
            'plos one': 3.7,
            'plos pathogens': 6.8,
            'scientific reports': 4.6,
            'scientific data': 8.9,
            'faseb journal': 4.8,
            'biochemical and biophysical research communications': 3.1,
            'biochemical pharmacology': 5.3,
            'biomedicine \u0026 pharmacotherapy': 7.5,
            'international journal of molecular sciences': 5.6,
            'acs nano': 17.1,
            'nano letters': 12.8,
            'the oncologist': 5.0,
            'bmc cancer': 4.4,
            'npj precision oncology': 7.9,
            'clinical and experimental medicine': 3.4,
            'discover oncology': 2.5,
            'critical reviews in oncology/hematology': 5.5,
            'world journal of gastrointestinal oncology': 3.8,
            'therapeutic advances in medical oncology': 4.7,
            'the journal of clinical investigation': 15.9,
            'journal of clinical investigation': 15.9,
            'oncology research and treatment': 2.8,
            'molecular pharmaceutics': 4.6,
            'med': 17.0,
            'journal for immunotherapy of cancer': 12.5,
            'haematologica': 10.1,
            'blood advances': 7.6,
            'biochimica et biophysica acta. reviews on cancer': 9.3,
            'the journal of physiology': 5.4,
            'journal of physiology': 5.4,
            'nuclear medicine communications': 2.2,
            'neoplasia': 5.0,
            'molecular cancer therapeutics': 5.7,
            'molecular biology reports': 3.2,
            'microbial pathogenesis': 3.8,
            'lung cancer': 5.3,
            'journal of thoracic oncology': 21.0,
            'peerj': 2.7,
            'international immunopharmacology': 5.6,
            'journal of translational medicine': 8.4,
            'journal of nanobiotechnology': 10.2,
            'molecules': 4.6,
            'international journal of cancer': 6.4,
            'carcinogenesis': 4.0,
            'drug resistance updates': 24.3,
            'journal of controlled release': 10.8,
            'advanced drug delivery reviews': 16.1,
            'biomaterials': 14.0,
            'acta pharmaceutica sinica b': 14.7,
            'journal of pharmaceutical analysis': 14.0,
            'british journal of pharmacology': 8.0,
            'drug discovery today': 7.4,
            'future medicinal chemistry': 3.6,
            'expert opinion on therapeutic targets': 5.4,
            'pharmacological research': 9.3,
            'pharmacology \u0026 therapeutics': 13.5,
            'biochemical society transactions': 3.8,
            'febs letters': 3.5,
            'febs journal': 5.5,
            'bioscience reports': 3.8,
            'biotechnology advances': 16.0,
            'trends in biochemical sciences': 14.0,
            'trends in pharmacological sciences': 13.8,
            'current opinion in chemical biology': 6.9,
            'current opinion in structural biology': 7.5,
            'structure': 5.7,
            'protein science': 8.0,
            'proteins': 4.0,
            'journal of molecular biology': 5.6,
            'biochimica et biophysica acta': 4.2,
            'archives of biochemistry and biophysics': 3.9,
            'frontiers in pharmacology': 5.6,
            'frontiers in oncology': 4.7,
            'frontiers in molecular biosciences': 5.0,
            'international journal of biochemistry \u0026 cell biology': 3.5,
            'life sciences': 6.1,
            'molecular therapy': 12.4,
            'molecular therapy-nucleic acids': 8.8,
            'nucleic acids research': 14.9,
            'rna': 5.1,
            'journal of molecular cell biology': 5.5,
            'cell death \u0026 disease': 9.0,
            'cell cycle': 4.3,
            'aging': 5.2,
            'oncogenesis': 6.2,
            'neoplasia': 5.0,
            'cancer science': 6.5,
            'cancer biology \u0026 medicine': 5.6,
            'acta biochimica et biophysica sinica': 3.7,
            'chinese journal of cancer research': 5.4,
            'protein \u0026 cell': 21.1,
            'signal transduction and targeted therapy': 39.3,
            'molecular cancer': 37.3,
            'theranostics': 12.4,
            'journal of experimental \u0026 clinical cancer research': 11.4,
            'journal of experimental medicine': 15.3,
            'cell metabolism': 31.4,
            'immunity': 32.4,
            'neuron': 17.0,
            'developmental cell': 11.8,
            'stem cell reports': 7.3,
            'embo journal': 11.4,
            'embo molecular medicine': 11.1,
            'embo reports': 7.7,
            'journal of cell biology': 8.0,
            'journal of cell science': 4.0,
            'traffic': 4.0,
            'autophagy': 14.3,
            'journal of proteome research': 4.4,
            'molecular \u0026 cellular proteomics': 7.4,
            'proteomics': 4.4,
            'journal of chromatography a': 4.1,
            'analytical chemistry': 7.0,
            'analytica chimica acta': 6.2,
            'talanta': 6.1,
            'analytical and bioanalytical chemistry': 4.3,
            'rapid communications in mass spectrometry': 2.5,
            'chemical communications': 4.9,
            'organic letters': 5.2,
            'organic \u0026 biomolecular chemistry': 3.9,
            'journal of organic chemistry': 3.6,
            'tetrahedron': 2.3,
            'tetrahedron letters': 2.4,
            'synthesis': 2.5,
            'synlett': 2.2,
            'arkivoc': 1.5,
            'beilstein journal of organic chemistry': 2.8,
            'current organic chemistry': 2.2,
            'chemical society reviews': 60.1,
            'accounts of chemical research': 18.3,
            'chemical reviews': 72.1,
            'natural product reports': 13.4,
            'journal of natural products': 3.3,
            'phytochemistry': 3.2,
            'fitoterapia': 3.4,
            'planta medica': 2.8,
            'phytochemistry letters': 2.0,
            'biochemical engineering journal': 4.4,
            'biotechnology and bioengineering': 4.5,
            'bioresource technology': 11.4,
            'biotechnology journal': 3.7,
            'microbial cell factories': 5.7,
            'applied microbiology and biotechnology': 5.0,
            'enzyme and microbial technology': 3.7,
            'process biochemistry': 4.0,
            'journal of biotechnology': 3.6,
            'new biotechnology': 3.7,
            'systems biology': 3.2,
            'computational biology': 4.5,
            'bioinformatics': 4.4,
            'briefings in bioinformatics': 9.5,
            'bmc bioinformatics': 3.0,
            'plos computational biology': 4.3,
            'journal of computational biology': 1.5,
            'biophysical journal': 3.4,
            'biopolymers': 2.5,
            'journal of biomolecular structure \u0026 dynamics': 3.0,
            'biochemistry': 2.9,
            'journal of chemical information and modeling': 5.6,
            'chemical biology \u0026 drug design': 3.5,
            'current topics in medicinal chemistry': 3.4,
            'mini-reviews in medicinal chemistry': 3.2,
            'combinatorial chemistry \u0026 high throughput screening': 1.8,
            'molecular diversity': 3.9,
            'journal of enzyme inhibition and medicinal chemistry': 4.5,
            'inflammation research': 6.7,
            'inflammopharmacology': 6.5,
            'international immunopharmacology': 5.6,
            'european journal of pharmacology': 5.0,
            'pharmacology': 1.9,
            'clinical pharmacology \u0026 therapeutics': 7.5,
            'clinical pharmacokinetics': 5.1,
            'british journal of clinical pharmacology': 3.8,
            'clinical pharmacology in drug development': 2.2,
            'fundamental \u0026 clinical pharmacology': 2.6,
            'biopharmaceutics \u0026 drug disposition': 2.0,
            'xenobiotica': 1.9,
            'drug metabolism and disposition': 4.4,
            'current drug metabolism': 2.8,
            'drug metabolism reviews': 4.0,
            'expert opinion on drug metabolism \u0026 toxicology': 3.8,
            'toxicology': 4.5,
            'archives of toxicology': 6.1,
            'food and chemical toxicology': 4.3,
            'regulatory toxicology and pharmacology': 3.3,
            'chemico-biological interactions': 5.2,
            'mutation research': 2.6,
            'toxicology in vitro': 3.3,
            'toxicology letters': 3.5,
            'environmental health perspectives': 10.4,
            'environmental science \u0026 technology': 11.4,
            'environmental toxicology and pharmacology': 3.5,
            'ecotoxicology and environmental safety': 6.8,
            'journal of hazardous materials': 13.6,
            'science of the total environment': 9.8,
            'chemosphere': 8.8,
            'ecotoxicology': 2.8,
            'aquatic toxicology': 5.2,
            'comparative biochemistry and physiology': 3.2,
            'marine environmental research': 3.0,
            'journal of experimental marine biology and ecology': 2.2,
            'fish \u0026 shellfish immunology': 4.7,
            'developmental \u0026 comparative immunology': 3.2,
            'immunology letters': 3.2,
            'molecular immunology': 3.6,
            'immunobiology': 3.2,
            'immunology': 4.5,
            'scandinavian journal of immunology': 3.1,
            'immunological investigations': 2.4,
            'clinical \u0026 experimental immunology': 4.4,
            'international reviews of immunology': 3.5,
            'autoimmunity reviews': 13.6,
            'journal of autoimmunity': 12.8,
            'lupus': 2.6,
            'clinical reviews in allergy \u0026 immunology': 9.0,
            'cytokine': 3.7,
            'journal of interferon \u0026 cytokine research': 2.0,
            'cytokine \u0026 growth factor reviews': 13.0,
            'growth factors': 3.5,
            'cellular signalling': 4.8,
            'cell communication and signaling': 8.4,
            'journal of receptor and signal transduction research': 1.8,
            'signaling': 3.2,
            'wires systems biology and medicine': 4.0,
            'systems biology and applications': 3.5,
            'npj systems biology and applications': 5.4,
            'computational and structural biotechnology journal': 6.0,
            'journal of molecular graphics \u0026 modelling': 2.5,
            'chemical research in toxicology': 3.7,
            'journal of chemical theory and computation': 5.7,
            'journal of computational chemistry': 3.4,
            'physical chemistry chemical physics': 3.0,
            'chemical physics letters': 2.7,
            'journal of physical chemistry b': 3.1,
            'journal of physical chemistry a': 2.8,
            'journal of chemical physics': 3.1,
            'molecular physics': 1.8,
            'chemical physics': 2.2,
            'theoretical chemistry accounts': 1.9,
            'journal of molecular modeling': 2.2,
            'molecular simulation': 2.0,
            'journal of computer-aided molecular design': 3.0,
            'molecular informatics': 3.6,
            'journal of cheminformatics': 8.0,
            'chemometrics and intelligent laboratory systems': 4.0,
            'analytical methods': 3.1,
            'analytical sciences': 1.6,
            'journal of separation science': 3.1,
            'electrophoresis': 3.0,
            'chromatographia': 2.1,
            'journal of chromatography b': 3.0,
            'journal of pharmaceutical and biomedical analysis': 3.4,
            'biomedical chromatography': 1.8,
            'journal of liquid chromatography \u0026 related technologies': 1.1,
            'lc gc north america': 1.5,
            'separation and purification reviews': 5.6,
            'separation and purification technology': 8.6,
            'adsorption': 2.9,
            'industrial \u0026 engineering chemistry research': 4.2,
            'chemical engineering science': 4.7,
            'aiche journal': 3.8,
            'chemical engineering journal': 15.1,
            'biotechnology progress': 2.8,
            'biotechnology and applied biochemistry': 2.4,
            'preparative biochemistry \u0026 biotechnology': 1.8,
            'applied biochemistry and biotechnology': 3.0,
            'journal of industrial microbiology \u0026 biotechnology': 3.4,
            'world journal of microbiology \u0026 biotechnology': 3.2,
            'annals of microbiology': 2.5,
            'extremophiles': 2.6,
            'antonie van leeuwenhoek': 2.6,
            'archives of microbiology': 2.5,
            'fems microbiology letters': 2.4,
            'fems microbiology reviews': 11.0,
            'microbiology': 3.0,
            'molecular microbiology': 3.3,
            'environmental microbiology': 5.1,
            'environmental microbiology reports': 4.0,
            'isme journal': 11.2,
            'microbiome': 15.5,
            'npj biofilms and microbiomes': 7.8,
            'gut microbiota': 10.0,
            'beneficial microbes': 4.0,
            'probiotics and antimicrobial proteins': 4.0,
            'anaerobe': 2.9,
            'research in microbiology': 2.5,
            'canadian journal of microbiology': 2.1,
            'current microbiology': 2.5,
            'letters in applied microbiology': 2.0,
            'journal of applied microbiology': 3.8,
            'journal of medical microbiology': 3.0,
            'clinical microbiology and infection': 13.3,
            'clinical microbiology reviews': 36.0,
            'clinical infectious diseases': 20.0,
            'journal of clinical microbiology': 9.4,
            'diagnostic microbiology and infectious disease': 2.9,
            'international journal of antimicrobial agents': 15.0,
            'journal of antimicrobial chemotherapy': 5.8,
            'antimicrobial agents and chemotherapy': 4.9,
            'international journal of infectious diseases': 8.4,
            'emerging infectious diseases': 16.0,
            'emerging microbes \u0026 infections': 8.4,
            'vector-borne and zoonotic diseases': 2.5,
            'epidemiology and infection': 3.5,
            'journal of infection': 8.0,
            'journal of hospital infection': 6.0,
            'infection control \u0026 hospital epidemiology': 4.0,
            'surgical infections': 1.8,
            'surgical oncology': 3.0,
            'european journal of surgical oncology': 3.8,
            'annals of surgical oncology': 3.8,
            'journal of surgical oncology': 2.5,
            'world journal of surgery': 3.5,
            'british journal of surgery': 11.0,
            'annals of surgery': 12.5,
            'surgery': 3.5,
            'american journal of surgery': 3.0,
            'archives of surgery': 3.5,
            'journal of the american college of surgeons': 5.5,
            'journal of surgical research': 2.5,
            'surgical endoscopy': 3.5,
            'surgical laparoscopy endoscopy \u0026 percutaneous techniques': 1.2,
            'obesity surgery': 3.5,
            'surgery for obesity and related diseases': 4.0,
            'digestive surgery': 2.5,
            'hpb': 3.0,
            'journal of gastrointestinal surgery': 3.0,
            'diseases of the colon \u0026 rectum': 3.8,
            'international journal of colorectal disease': 2.5,
            'colorectal disease': 2.5,
            'surgical oncology clinics of north america': 1.8,
            'journal of pediatric surgery': 1.8,
            'pediatric surgery international': 1.5,
            'journal of pediatric gastroenterology and nutrition': 2.8,
            'journal of pediatric oncology nursing': 1.2,
            'pediatric blood \u0026 cancer': 3.5,
            'pediatric hematology and oncology': 1.5,
            'pediatrics': 7.0,
            'journal of pediatrics': 4.0,
            'archives of disease in childhood': 4.0,
            'acta paediatrica': 2.0,
            'european journal of pediatrics': 2.0,
            'journal of child psychology and psychiatry': 8.0,
            'journal of the american academy of child \u0026 adolescent psychiatry': 13.0,
            'child development': 5.0,
            'developmental psychology': 4.0,
            'developmental science': 4.0,
            'infant behavior \u0026 development': 2.0,
            'early human development': 2.0,
            'neonatology': 2.5,
            'journal of perinatology': 2.0,
            'journal of maternal-fetal \u0026 neonatal medicine': 2.0,
            'bjog': 5.5,
            'american journal of obstetrics \u0026 gynecology': 8.0,
            'obstetrics \u0026 gynecology': 7.0,
            'fertility and sterility': 6.0,
            'human reproduction': 6.0,
            'human reproduction update': 17.0,
            'reproductive biomedicine online': 4.0,
            'journal of assisted reproduction and genetics': 3.0,
            'reproductive sciences': 2.5,
            'reproductive toxicology': 3.0,
            'systems biology in reproductive medicine': 2.0,
            'andrology': 3.0,
            'asian journal of andrology': 2.5,
            'journal of andrology': 2.0,
            'international journal of andrology': 2.0,
            'journal of sexual medicine': 3.0,
            'sexual medicine reviews': 3.0,
            'journal of endocrinology': 4.0,
            'journal of clinical endocrinology \u0026 metabolism': 6.0,
            'endocrinology': 4.5,
            'molecular endocrinology': 4.0,
            'endocrine reviews': 22.0,
            'trends in endocrinology \u0026 metabolism': 10.0,
            'best practice \u0026 research clinical endocrinology \u0026 metabolism': 4.0,
            'pituitary': 4.0,
            'thyroid': 6.0,
            'journal of bone and mineral research': 6.5,
            'bone': 4.0,
            'osteoporosis international': 4.0,
            'calcified tissue international': 3.5,
            'journal of bone and mineral metabolism': 2.5,
            'bone research': 12.0,
            'diabetes': 8.0,
            'diabetologia': 10.0,
            'diabetes care': 19.0,
            'molecular metabolism': 7.0,
            'diabetes \u0026 metabolism': 4.0,
            'diabetic medicine': 4.0,
            'obesity': 5.0,
            'international journal of obesity': 5.5,
            'obesity reviews': 10.0,
            'clinical endocrinology': 3.5,
            'european journal of endocrinology': 5.5,
            'journal of endocrinological investigation': 3.5,
            'endocrine': 3.0,
            'endocrine connections': 3.0,
            'hormones and behavior': 3.5,
            'psychoneuroendocrinology': 4.5,
            'frontiers in endocrinology': 5.2,
            'frontiers in neuroscience': 4.7,
            'neuroscience': 3.5,
            'neuroscience letters': 2.5,
            'journal of neuroscience': 6.0,
            'neuroscience \u0026 biobehavioral reviews': 8.5,
            'progress in neurobiology': 9.0,
            'brain research': 3.5,
            'brain research bulletin': 3.5,
            'neurochemistry international': 4.0,
            'journal of neurochemistry': 4.5,
            'neuropharmacology': 5.0,
            'psychopharmacology': 3.5,
            'neuropsychopharmacology': 8.0,
            'biological psychiatry': 12.0,
            'molecular psychiatry': 13.0,
            'journal of psychiatric research': 4.0,
            'psychiatry research': 3.0,
            'schizophrenia research': 4.0,
            'schizophrenia bulletin': 7.0,
            'journal of affective disorders': 6.0,
            'psychiatry and clinical neurosciences': 3.5,
            'general hospital psychiatry': 3.5,
            'psychosomatic medicine': 4.5,
            'journal of psychosomatic research': 4.0,
            'psychotherapy and psychosomatics': 16.0,
            'world psychiatry': 73.0,
            'lancet psychiatry': 30.0,
            'jama psychiatry': 25.0,
            'american journal of psychiatry': 18.0,
            'psychological medicine': 7.0,
            'journal of abnormal psychology': 6.0,
            'journal of consulting and clinical psychology': 6.0,
            'clinical psychology review': 12.0,
            'behaviour research and therapy': 4.0,
            'journal of behavior therapy and experimental psychiatry': 2.5,
            'cognitive therapy and research': 2.5,
            'journal of cognitive neuroscience': 4.0,
            'cognitive neuropsychology': 2.5,
            'neuropsychologia': 3.0,
            'cortex': 4.0,
            'brain and language': 2.5,
            'neuropsychology review': 5.0,
            'archives of clinical neuropsychology': 3.5,
            'journal of the international neuropsychological society': 3.0,
            'clinical neuropsychologist': 2.5,
            'neurocase': 1.5,
            'cognitive neuropsychiatry': 2.5,
            'social cognitive and affective neuroscience': 4.0,
            'human brain mapping': 5.0,
            'neuroimage': 7.0,
            'brain connectivity': 3.0,
            'magnetic resonance imaging': 2.5,
            'journal of magnetic resonance imaging': 4.0,
            'neuroradiology': 2.5,
            'american journal of neuroradiology': 3.5,
            'radiology': 29.0,
            'european radiology': 5.0,
            'investigative radiology': 5.0,
            'academic radiology': 3.5,
            'journal of computer assisted tomography': 2.0,
            'surgical neurology international': 1.5,
            'world neurosurgery': 2.5,
            'journal of neurosurgery': 5.0,
            'neurosurgery': 5.5,
            'acta neurochirurgica': 2.0,
            'neurosurgical review': 3.0,
            'spine': 3.0,
            'spine journal': 4.0,
            'european spine journal': 3.0,
            'journal of neurosurgery: spine': 3.5,
            'journal of spinal disorders \u0026 techniques': 2.0,
            'neurosurgical focus': 3.5,
            'neuromodulation': 3.0,
            'pain': 6.0,
            'pain medicine': 3.5,
            'regional anesthesia and pain medicine': 4.0,
            'clinical journal of pain': 3.0,
            'european journal of pain': 3.5,
            'headache': 4.0,
            'cephalalgia': 5.0,
            'journal of headache and pain': 7.0,
            'stroke': 7.0,
            'stroke and vascular neurology': 5.0,
            'cerebrovascular diseases': 2.5,
            'international journal of stroke': 4.0,
            'journal of stroke': 4.0,
            'frontiers in neurology': 3.4,
            'neurology': 9.0,
            'annals of neurology': 11.0,
            'brain': 15.0,
            'lancet neurology': 48.0,
            'jama neurology': 29.0,
            'current opinion in neurology': 4.5,
            'practical neurology': 3.0,
            'neurology: clinical practice': 2.5,
            'multiple sclerosis journal': 5.0,
            'multiple sclerosis and related disorders': 3.0,
            'journal of neurology': 4.0,
            'journal of neurology neurosurgery \u0026 psychiatry': 13.0,
            'european journal of neurology': 5.0,
            'neurological sciences': 3.0,
            'clinical neurology and neurosurgery': 2.0,
            'parkinsonism \u0026 related disorders': 4.0,
            'movement disorders': 9.0,
            'movement disorders clinical practice': 3.0,
            'alzheimers research \u0026 therapy': 7.0,
            'neurobiology of aging': 5.0,
            'neurobiology of disease': 5.0,
            'experimental neurology': 5.0,
            'glia': 6.0,
            'journal of neuroscience research': 4.0,
            'neuroscience research': 2.5,
            'developmental neuroscience': 2.5,
            'journal of developmental origins of health and disease': 2.5,
            'birth defects research': 2.0,
            'teratology': 2.0,
            'pediatric research': 3.5,
            'biology of the neonate': 2.0,
            'placenta': 3.5,
            'reproduction': 3.5,
            'molecular human reproduction': 4.0,
            'journal of reproductive immunology': 3.5,
            'american journal of reproductive immunology': 3.5,
            'journal of reproductive and developmental': 2.0,
            'reproductive medicine and biology': 2.5,
            'journal of reproduction and development': 2.0,
            'reproduction in domestic animals': 2.0,
            'theriogenology': 2.5,
            'animal reproduction science': 2.0,
            'molecular reproduction and development': 2.5,
            'gamete research': 1.5,
            'andrologia': 2.0,
            'in vitro cellular \u0026 developmental biology': 2.0,
            'stem cells': 5.5,
            'stem cells and development': 3.5,
            'cell stem cell': 25.3,
            'stem cell research': 2.5,
            'regenerative medicine': 3.5,
            'npj regenerative medicine': 10.0,
            'tissue engineering': 4.0,
            'tissue engineering part a': 4.0,
            'tissue engineering part b: reviews': 4.5,
            'tissue engineering part c: methods': 3.5,
            'cytotherapy': 4.0,
            'stem cells translational medicine': 6.5,
            'cell transplantation': 3.5,
            'regenerative therapy': 3.0,
            'acta biomaterialia': 10.0,
            'journal of the mechanical behavior of biomedical materials': 3.5,
            'dental materials': 5.0,
            'journal of dentistry': 4.0,
            'dental materials journal': 2.0,
            'journal of prosthetic dentistry': 3.0,
            'journal of prosthodontics': 2.5,
            'international journal of prosthodontics': 2.0,
            'journal of oral rehabilitation': 3.0,
            'clinical oral implants research': 5.0,
            'journal of clinical periodontology': 6.0,
            'journal of periodontology': 3.5,
            'periodontology 2000': 8.0,
            'journal of periodontal research': 3.5,
            'molecular oral microbiology': 2.5,
            'oral microbiology and immunology': 2.0,
            'journal of endodontics': 3.5,
            'international endodontic journal': 4.0,
            'journal of oral \u0026 maxillofacial surgery': 2.5,
            'international journal of oral and maxillofacial surgery': 2.5,
            'british journal of oral and maxillofacial surgery': 2.0,
            'oral oncology': 4.5,
            'oral surgery oral medicine oral pathology and oral radiology': 2.0,
            'head and neck': 3.5,
            'head \u0026 neck': 3.5,
            'laryngoscope': 3.0,
            'otology \u0026 neurotology': 2.5,
            'international journal of pediatric otorhinolaryngology': 1.8,
            'american journal of otolaryngology': 1.8,
            'european archives of oto-rhino-laryngology': 2.0,
            'journal of laryngology and otology': 1.5,
            'ophthalmology': 13.0,
            'american journal of ophthalmology': 5.0,
            'investigative ophthalmology \u0026 visual science': 5.0,
            'british journal of ophthalmology': 5.0,
            'retina': 4.0,
            'journal of cataract and refractive surgery': 3.5,
            'journal of refractive surgery': 2.5,
            'cornea': 3.0,
            'ocular surface': 4.0,
            'contact lens \u0026 anterior eye': 3.0,
            'optometry and vision science': 2.0,
            'vision research': 2.0,
            'experimental eye research': 3.0,
            'molecular vision': 2.5,
            'documenta ophthalmologica': 2.0,
            'current eye research': 2.5,
            'eye': 3.5,
            'acta ophthalmologica': 3.5,
            'clinical \u0026 experimental ophthalmology': 3.5,
            'ophthalmic and physiological optics': 2.5,
            'strabismus': 1.5,
            'optometry': 1.2,
            'journal of american association for pediatric ophthalmology and strabismus': 1.8,
            'ophthalmic plastic and reconstructive surgery': 2.0,
            'ophthalmic genetics': 1.5,
            'ocular immunology and inflammation': 2.5,
            'international ophthalmology': 2.0,
            'ophthalmologica': 2.0,
            'klinische monatsblatter fur augenheilkunde': 1.0,
            'jama ophthalmology': 8.0,
            'progress in retinal and eye research': 15.0,
            'survey of ophthalmology': 4.5,
            'current opinion in ophthalmology': 3.0,
            'archives of ophthalmology': 3.5,
            'journal of glaucoma': 3.0,
            'glaucoma': 2.0,
            'international glaucoma review': 1.5,
            'veterinary ophthalmology': 1.8,
            'veterinary and comparative ophthalmology': 1.5,
            'journal of comparative pathology': 2.0,
            'veterinary pathology': 2.5,
            'veterinary immunology and immunopathology': 2.0,
            'veterinary microbiology': 3.0,
            'veterinary parasitology': 2.5,
            'preventive veterinary medicine': 2.5,
            'research in veterinary science': 2.0,
            'veterinary journal': 2.5,
            'veterinary record': 2.0,
            'journal of veterinary internal medicine': 3.0,
            'journal of veterinary diagnostic investigation': 2.0,
            'veterinary clinical pathology': 2.0,
            'toxicologic pathology': 2.0,
            'journal of toxicologic pathology': 1.5,
            'journal of pharmacological and toxicological methods': 2.5,
            'journal of applied toxicology': 3.0,
            'human \u0026 experimental toxicology': 2.0,
            'cutaneous and ocular toxicology': 1.8,
            'birth defects research part b': 2.0,
            'toxicology mechanisms and methods': 2.5,
            'journal of biochemical and molecular toxicology': 3.5,
            'journal of toxicology and environmental health': 2.5,
            'journal of toxicology': 1.5,
            'toxicology international': 1.0,
            'drug and chemical toxicology': 2.0,
            'journal of analytical toxicology': 3.0,
            'forensic science international': 2.0,
            'forensic science international: genetics': 4.0,
            'international journal of legal medicine': 2.5,
            'american journal of forensic medicine and pathology': 1.5,
            'journal of forensic sciences': 2.0,
            'legal medicine': 2.0,
            'journal of clinical forensic medicine': 1.5,
            'forensic science medicine and pathology': 2.0,
            'journal of forensic and legal medicine': 1.8,
            'medicine science and the law': 1.2,
            'science \u0026 justice': 2.0,
            'journal of forensic odonto-stomatology': 0.5,
            'academic emergency medicine': 4.0,
            'annals of emergency medicine': 6.0,
            'emergency medicine journal': 3.0,
            'american journal of emergency medicine': 2.5,
            'journal of emergency medicine': 2.0,
            'european journal of emergency medicine': 2.0,
            'international journal of emergency medicine': 2.0,
            'prehospital emergency care': 3.0,
            'resuscitation': 6.0,
            'critical care medicine': 9.0,
            'intensive care medicine': 19.0,
            'critical care': 19.0,
            'journal of critical care': 3.0,
            'australian critical care': 2.0,
            'dimensions of critical care nursing': 1.5,
            'heart \u0026 lung': 2.5,
            'american journal of critical care': 3.5,
            'progress in cardiovascular diseases': 4.0,
            'cardiology clinics': 2.5,
            'heart rhythm': 5.0,
            'journal of cardiovascular electrophysiology': 3.0,
            'circulation': 37.0,
            'circulation research': 17.0,
            'journal of the american college of cardiology': 24.0,
            'european heart journal': 29.0,
            'jacc: cardiovascular interventions': 12.0,
            'jacc: heart failure': 12.0,
            'jacc: clinical electrophysiology': 6.0,
            'jacc: basic to translational science': 6.0,
            'jacc: cardiooncology': 8.0,
            'jacc: case reports': 2.0,
            'jacc: cardiovascular imaging': 14.0,
            'journal of nuclear cardiology': 3.0,
            'journal of thoracic and cardiovascular surgery': 6.0,
            'annals of thoracic surgery': 4.5,
            'european journal of cardio-thoracic surgery': 4.0,
            'interactive cardiovascular and thoracic surgery': 2.0,
            'innovations': 2.0,
            'sem thoracic cardiovascular surgery': 2.0,
            'thoracic surgery clinics': 2.0,
            'respiratory medicine': 3.5,
            'respiratory research': 5.0,
            'chest': 10.0,
            'thorax': 10.0,
            'european respiratory journal': 17.0,
            'american journal of respiratory and critical care medicine': 24.0,
            'journal of applied physiology': 3.5,
            'respiratory physiology \u0026 neurobiology': 2.5,
            'pulmonary pharmacology \u0026 therapeutics': 3.0,
            'copd': 3.0,
            'chronic respiratory disease': 3.0,
            'npj primary care respiratory medicine': 3.0,
            'therapeutic advances in respiratory disease': 3.5,
            'multidisciplinary respiratory medicine': 2.0,
            'clinical respiratory journal': 2.5,
            'respirology': 6.0,
            'respirology case reports': 1.5,
            'lung': 3.0,
            'lung cancer': 6.0,
            'journal of thoracic oncology': 13.0,
            'clinical lung cancer': 4.0,
            'translational lung cancer research': 4.0,
            'journal of thoracic disease': 3.0,
            'annals of thoracic medicine': 2.0,
            'pioneer thoracic surgery': 1.5,
            'journal of gastrointestinal and liver diseases': 2.5,
            'journal of clinical gastroenterology': 3.0,
            'clinical gastroenterology and hepatology': 11.0,
            'american journal of gastroenterology': 12.0,
            'gastroenterology': 33.0,
            'gut': 31.0,
            'hepatology': 17.0,
            'journal of hepatology': 26.0,
            'liver international': 8.0,
            'liver transplantation': 5.0,
            'transplantation': 5.0,
            'american journal of transplantation': 8.0,
            'transplant international': 3.0,
            'clinical transplantation': 2.5,
            'transplantation reviews': 3.5,
            'transplantation direct': 2.0,
            'xenotransplantation': 3.5,
            'nephrology dialysis transplantation': 5.0,
            'kidney international': 19.0,
            'american journal of kidney diseases': 11.0,
            'journal of the american society of nephrology': 14.0,
            'clinical journal of the american society of nephrology': 8.0,
            'nephrology': 3.0,
            'pediatric nephrology': 3.0,
            'sem nephrology': 3.0,
            'adv chronic kidney disease': 3.0,
            'journal of renal nutrition': 3.0,
            'kidney \u0026 blood pressure research': 2.5,
            'blood purification': 2.5,
            'hemodialysis international': 2.5,
            'peritoneal dialysis international': 3.0,
            'artificial organs': 3.0,
            'asaio journal': 3.0,
            'therapeutic apheresis and dialysis': 2.0,
            'international urology and nephrology': 2.0,
            'urologic oncology': 3.5,
            'european urology': 24.0,
            'journal of urology': 6.0,
            'urology': 3.0,
            'bjui': 5.0,
            'prostate': 4.0,
            'prostate cancer and prostatic diseases': 5.0,
            'international journal of urology': 2.5,
            'scandinavian journal of urology': 2.0,
            'urology case reports': 1.5,
            'canadian journal of urology': 1.5,
            'investigative and clinical urology': 2.0,
            'world journal of urology': 3.5,
            'archives of dermatological research': 2.5,
            'british journal of dermatology': 10.0,
            'journal of the american academy of dermatology': 13.0,
            'journal of investigative dermatology': 7.0,
            'dermatologic therapy': 3.0,
            'international journal of dermatology': 2.5,
            'clinical and experimental dermatology': 3.0,
            'dermatology': 3.5,
            'acta dermato-venereologica': 4.0,
            'journal of the european academy of dermatology and venereology': 9.0,
            'american journal of clinical dermatology': 5.0,
            'contact dermatitis': 4.0,
            'photodermatology photoimmunology \u0026 photomedicine': 3.0,
            'experimental dermatology': 4.0,
            'dermatologic surgery': 3.0,
            'laser surgery and medicine': 3.0,
            'lasers in surgery and medicine': 3.0,
            'lasers in medical science': 3.0,
            'photodiagnosis and photodynamic therapy': 3.0,
            'journal of photochemistry and photobiology b: biology': 4.0,
            'journal of photochemistry and photobiology b biology': 4.0,
            'journal of photochemistry and photobiology': 3.0,
            'photochemistry and photobiology': 3.0,
            'photochemical \u0026 photobiological sciences': 3.0,
            'radiation research': 3.0,
            'radiation and environmental biophysics': 2.0,
            'health physics': 1.5,
            'international journal of radiation biology': 3.0,
            'journal of radiological protection': 2.0,
            'british journal of radiology': 3.0,
            'radiographics': 5.0,
            'seminiars in radiation oncology': 4.0,
            'international journal of radiation oncology biology physics': 7.0,
            'radiotherapy and oncology': 5.0,
            'practical radiation oncology': 3.5,
            'journal of applied clinical medical physics': 1.5,
            'medical physics': 4.0,
            'physics in medicine and biology': 3.5,
            'journal of magnetic resonance': 2.5,
            'nmr in biomedicine': 3.0,
            'magnetic resonance in medicine': 4.0,
            'journal of cardiovascular magnetic resonance': 6.0,
            'magnetic resonance in chemistry': 2.0,
            'concepts in magnetic resonance': 2.0,
            'european journal of radiology': 3.0,
            'skeletal radiology': 2.0,
            'emergency radiology': 2.0,
            'journal of digital imaging': 2.0,
            'clinical radiology': 3.0,
            'abdominal radiology': 3.0,
            'pediatric radiology': 2.5,
            'cardiovascular and interventional radiology': 2.5,
            'european radiology experimental': 3.0,
            'quantitative imaging in medicine and surgery': 3.0,
            'insights into imaging': 5.0,
            'journal of ultrasound in medicine': 2.5,
            'ultrasound in obstetrics \u0026 gynecology': 7.0,
            'ultraschall in der medizin': 3.0,
            'journal of clinical ultrasound': 1.5,
            'medical ultrasonography': 2.0,
            'ultrasonics': 3.5,
            'ultrasonics sonochemistry': 9.0,
            'journal of ultrasound': 2.0,
            'current medical imaging': 2.0,
            'current medical imaging reviews': 2.0,
            'tomography': 3.5,
            'molecular imaging and biology': 4.0,
            'journal of nuclear medicine': 11.0,
            'european journal of nuclear medicine and molecular imaging': 10.0,
            'nuclear medicine and biology': 3.0,
            'clinical nuclear medicine': 3.0,
            'hellenic journal of nuclear medicine': 1.0,
            'world journal of nuclear medicine': 1.5,
            'nuclear medicine communications': 2.0,
            'journal of neuroimaging': 2.0,
            'neuroimage: clinical': 4.0,
            'neuroimage clinical': 4.0,
            'alzheimers dementia diagnosis': 6.0,
            'journal of vascular and interventional radiology': 3.5,
            'cardio-vascular and interventional radiology': 2.5,
            'diagnostic and interventional radiology': 2.0,
            'international journal of hyperthermia': 3.0,
            'hyperthermia': 2.5,
            'thermal medicine': 1.5,
            'computers in biology and medicine': 7.0,
            'computers methods and programs in biomedicine': 6.0,
            'international journal of medical informatics': 4.0,
            'journal of biomedical informatics': 7.0,
            'artificial intelligence in medicine': 7.0,
            'medical image analysis': 13.0,
            'ieee transactions on medical imaging': 11.0,
            'ieee journal of biomedical and health informatics': 7.0,
            'npj digital medicine': 15.0,
            'journal of medical internet research': 7.0,
            'bmj health \u0026 care informatics': 4.0,
            'bmc medical informatics and decision making': 3.0,
            'journal of the american medical informatics association': 7.0,
            'international journal of medical robotics and computer assisted surgery': 3.0,
            'international journal of computer assisted radiology and surgery': 4.0,
            'computer aided surgery': 2.5,
            'surgical innovation': 2.5,
            'journal of robotic surgery': 3.0,
            'robotic surgery: research and reviews': 2.0,
            'journal of healthcare engineering': 3.0,
            'biomedical engineering online': 3.0,
            'journal of biomechanics': 3.0,
            'journal of biomechanical engineering': 2.5,
            'clinical biomechanics': 3.0,
            'medical engineering \u0026 physics': 2.5,
            'annals of biomedical engineering': 3.5,
            'ieee transactions on biomedical engineering': 4.0,
            'frontiers in bioengineering and biotechnology': 6.0,
            'biofabrication': 9.0,
            'bioengineering': 4.0,
            'bioengineering \u0026 translational medicine': 8.0,
            'annual review of biomedical engineering': 12.0,
            'tissue engineering and regenerative medicine': 4.0,
            'artificial cells nanomedicine and biotechnology': 6.0,
            'regenerative biomaterials': 6.0,
            'bioactive materials': 18.0,
            'materials today bio': 8.0,
            'bio-design and manufacturing': 6.0,
            'nanoscale': 6.0,
            'nanoscale horizons': 8.0,
            'nanomedicine': 5.0,
            'international journal of nanomedicine': 7.0,
            'nanomedicine: nanotechnology biology and medicine': 5.0,
            'journal of drug targeting': 3.5,
            'drug delivery': 6.0,
            'expert opinion on drug delivery': 5.0,
            'molecular pharmaceutics': 4.5,
            'aaps pharmscitech': 4.0,
            'aaps journal': 4.0,
            'international journal of pharmaceutics': 6.0,
            'european journal of pharmaceutics and biopharmaceutics': 4.5,
            'pharmaceutical research': 3.8,
            'pharmaceutics': 5.0,
            'asian journal of pharmaceutical sciences': 10.0,
            'drug development and industrial pharmacy': 3.0,
            'drug development research': 2.5,
            'current pharmaceutical design': 3.0,
            'current drug targets': 3.0,
            'current drug delivery': 3.0,
            'current pharmaceutical biotechnology': 3.0,
            'current protein \u0026 peptide science': 3.0,
            'current enzyme inhibition': 2.0,
            'current computer-aided drug design': 2.5,
            'letters in drug design \u0026 discovery': 1.5,
            'recent patents on anti-cancer drug discovery': 2.5,
            'anti-cancer agents in medicinal chemistry': 3.0,
            'anti-cancer drugs': 3.0,
            'investigational new drugs': 3.5,
            'clinical cancer drugs': 2.5,
            'cancer chemotherapy and pharmacology': 3.5,
            'journal of chemotherapy': 2.0,
            'supportive care in cancer': 3.5,
            'journal of pain and symptom management': 4.0,
            'palliative medicine': 4.0,
            'bmc palliative care': 3.0,
            'american journal of hospice \u0026 palliative medicine': 2.0,
            'journal of palliative medicine': 2.5,
            'journal of palliative care': 1.5,
            'progress in palliative care': 1.5,
            'psycho-oncology': 4.0,
            'journal of psychosocial oncology': 2.0,
            'cancer nursing': 2.5,
            'european journal of oncology nursing': 3.0,
            'oncology nursing forum': 2.0,
            'sem oncology nursing': 2.5,
            'asia-pacific journal of oncology nursing': 2.0,
            'oncotarget': 4.0,
            'oncotargets and therapy': 4.0,
            'cancer management and research': 3.0,
            'cancer informatics': 2.5,
            'cancer epidemiology': 3.5,
            'cancer causes \u0026 control': 3.0,
            'cancer epidemiology biomarkers \u0026 prevention': 4.0,
            'british journal of cancer': 8.0,
            'gynecologic oncology': 5.0,
            'gynecologic oncology reports': 2.5,
            'international journal of gynecological cancer': 3.0,
            'journal of lower genital tract disease': 2.0,
            'journal of gynecologic oncology': 4.0,
            'international journal of gynecological pathology': 2.5,
            'cytopathology': 2.5,
            'diagnostic cytopathology': 2.0,
            'acta cytologica': 2.0,
            'journal of clinical pathology': 3.0,
            'american journal of clinical pathology': 3.5,
            'histopathology': 4.5,
            'journal of pathology': 7.0,
            'laboratory investigation': 5.0,
            'modern pathology': 8.0,
            'virchows archiv': 3.5,
            'pathology': 3.0,
            'pathology international': 2.5,
            'pathology research and practice': 2.5,
            'annals of diagnostic pathology': 2.0,
            'diagnostic pathology': 2.5,
            'experimental and molecular pathology': 3.5,
            'ultrastructural pathology': 1.5,
            'applied immunohistochemistry \u0026 molecular morphology': 1.8,
            'journal of histochemistry and cytochemistry': 3.0,
            'histochemistry and cell biology': 4.0,
            'acta histochemica': 2.0,
            'journal of molecular histology': 2.5,
            'immunohistochemistry': 2.5,
            'journal of immunological methods': 2.5,
            'methods': 4.0,
            'analytical biochemistry': 3.5,
            'biochemistry and molecular biology education': 1.5,
            'biochemistry and cell biology': 3.0,
            'biochemistry moscow': 2.0,
            'biochimie': 3.5,
            'febs open bio': 2.5,
            'bioscience biotechnology and biochemistry': 2.0,
            'biotechnology letters': 2.5,
            'world journal of microbiology and biotechnology': 3.5,
            'microbial pathogenesis': 3.5,
            'infection and immunity': 4.0,
            'infection': 3.5,
            'surgery today': 2.0,
            'techniques in coloproctology': 2.5,
            'journal of plastic reconstructive \u0026 aesthetic surgery': 3.0,
            'journal of plastic surgery and hand surgery': 1.5,
            'journal of reconstructive microsurgery': 2.5,
            'microsurgery': 2.5,
            'hand surgery': 1.5,
            'journal of hand surgery': 2.0,
            'journal of hand surgery (european volume)': 2.0,
            'hand clinics': 1.5,
            'journal of burn care \u0026 research': 2.0,
            'burns': 3.0,
            'wound repair and regeneration': 3.5,
            'international wound journal': 3.0,
            'advances in wound care': 6.0,
            'wounds': 2.0,
            'journal of wound care': 2.5,
            'ostomy wound management': 1.5,
            'journal of vascular surgery': 4.0,
            'european journal of vascular and endovascular surgery': 5.0,
            'annals of vascular surgery': 2.0,
            'vascular': 1.5,
            'journal of endovascular therapy': 3.0,
            'journal of cardiovascular surgery': 2.5,
            'journal of cardiothoracic surgery': 2.0,
            'journal of cardiac surgery': 1.5,
            'heart surgery forum': 1.0,
            'sem cardiothoracic vascular anesthesia': 1.5,
            'journal of extra-corporeal technology': 1.0,
            'perfusion': 2.0,
            'journal of thoracic imaging': 2.5,
            'operative techniques in thoracic and cardiovascular surgery': 1.5,
            'journal of pediatric urology': 2.0,
            'journal of pediatric orthopaedics': 2.0,
            'journal of pediatric orthopaedics b': 1.5,
            'pediatric neurology': 3.5,
            'pediatric allergy and immunology': 3.5,
            'pediatric pulmonology': 3.0,
            'pediatric critical care medicine': 4.0,
            'pediatric emergency care': 1.5,
            'clinical pediatrics': 1.5,
            'pediatrics international': 1.5,
        }
    
    def _load_cache(self) -> Dict:
        """加载缓存的影响因子数据"""
        if os.path.exists(self.cache_file):
            try:
                with open(self.cache_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except:
                return {}
        return {}
    
    def _save_cache(self):
        """保存缓存"""
        try:
            with open(self.cache_file, 'w', encoding='utf-8') as f:
                json.dump(self.cache, f, ensure_ascii=False, indent=2)
        except Exception as e:
            print(f"Error saving cache: {e}")
    
    def get_impact_factor(self, journal_name: str) -> Optional[float]:
        """
        获取期刊影响因子
        
        Args:
            journal_name: 期刊名称
            
        Returns:
            影响因子，如果未找到则返回None
        """
        if not journal_name:
            return None
        
        journal_lower = journal_name.lower().strip()
        
        # 1. 首先检查缓存
        if journal_lower in self.cache:
            return self.cache[journal_lower]
        
        # 2. 检查常用期刊列表 - 优先精确匹配
        if journal_lower in self.common_journals:
            if_value = self.common_journals[journal_lower]
            self.cache[journal_lower] = if_value
            return if_value
        
        # 2.5 清理期刊名称后再次尝试精确匹配
        # 移除括号及其内容（如 "Advanced science (Weinheim...)" -> "advanced science"）
        journal_clean = _RE_PARENS.sub('', journal_lower).strip()
        journal_clean = _RE_BRACKETS.sub('', journal_clean).strip()
        journal_clean = _RE_TRAILING_COLON.sub('', journal_clean).strip()
        
        if journal_clean and journal_clean in self.common_journals:
            if_value = self.common_journals[journal_clean]
            self.cache[journal_lower] = if_value
            return if_value
        
        # 3. 尝试从外部API获取实时数据
        external_if = self.fetch_from_external_source(journal_name)
        if external_if is not None:
            self.cache[journal_lower] = external_if
            self._save_cache()
            return external_if
        
        # 4. 尝试模糊匹配 - 优先最长匹配（最精确）
        best_match = None
        best_match_length = 0
        
        for known_journal, if_value in self.common_journals.items():
            # 检查是否是子串匹配
            if known_journal in journal_lower or journal_lower in known_journal:
                match_length = min(len(known_journal), len(journal_lower))
                # 选择最长的匹配（最精确）
                if match_length > best_match_length:
                    best_match = if_value
                    best_match_length = match_length
        
        if best_match is not None:
            self.cache[journal_lower] = best_match
            return best_match
        
        # 5. 对于bioRxiv/medRxiv返回0
        if 'biorxiv' in journal_lower or 'medrxiv' in journal_lower:
            self.cache[journal_lower] = 0.0
            return 0.0
        
        # 未找到
        return None
    
    def _fetch_from_crossref(self, journal_name: str) -> Optional[float]:
        """
        从Crossref API获取期刊ISSN，然后尝试从其他源获取IF
        Crossref不直接提供影响因子，但可以获取期刊元数据
        """
        try:
            url = "https://api.crossref.org/journals"
            params = {
                'query': journal_name,
                'rows': 5
            }
            
            response = requests.get(url, params=params, timeout=10)
            if response.status_code == 200:
                data = response.json()
                items = data.get('message', {}).get('items', [])
                
                if items and len(items) > 0:
                    # 获取第一个匹配期刊的ISSN
                    item = items[0]
                    issns = item.get('ISSN', [])
                    if issns:
                        # 尝试用ISSN获取IF
                        for issn in issns:
                            if_value = self._fetch_if_by_issn(issn)
                            if if_value is not None:
                                return if_value
            
            return None
        except Exception as e:
            print(f"Crossref fetch error for {journal_name}: {e}")
            return None
    
    def _fetch_if_by_issn(self, issn: str) -> Optional[float]:
        """
        通过ISSN获取影响因子
        尝试多个免费API
        """
        # 尝试Scopus CiteScore API (需要API key)
        # 尝试Dimensions API (需要API key)
        # 尝试OpenAlex API (免费，提供引用指标但不一定是传统IF)
        
        try:
            # 使用OpenAlex API获取引用数据
            url = f"https://api.openalex.org/sources/issn:{issn}"
            response = requests.get(url, timeout=10)
            
            if response.status_code == 200:
                data = response.json()
                # OpenAlex提供2年引用中位数作为替代指标
                # 虽然不是传统IF，但可作为参考
                cited_by_count = data.get('cited_by_count', 0)
                works_count = data.get('works_count', 1)
                
                # 简单的引用/文章比率 (不是标准IF计算)
                if works_count > 0:
                    ratio = cited_by_count / works_count
                    # 这是一个粗略估算，实际IF通常小于这个比率
                    # 返回None因为我们无法准确计算IF
                    return None
        except Exception:
            pass
        
        return None
    
    def fetch_from_external_source(self, journal_name: str) -> Optional[float]:
        """
        尝试从外部数据源获取影响因子
        支持多个免费和付费API
        """
        if_value = self._fetch_from_crossref(journal_name)
        if if_value is not None:
            return if_value
        
        # 可以在这里添加更多API
        # 1. Scopus API (需要SCOPUS_API_KEY环境变量)
        # 2. Web of Science API (需要订阅)
        # 3. Journal Citation Reports API (需要订阅)
        
        return None
    
    def batch_get_impact_factors(self, papers: List[Dict]) -> List[Dict]:
        """批量获取影响因子"""
        for paper in papers:
            journal = paper.get('journal', '')
            if_value = self.get_impact_factor(journal)
            # 如果没有找到影响因子，默认为0.0
            if if_value is None:
                if_value = 0.0
            paper['impact_factor'] = if_value
        
        # 保存缓存
        self._save_cache()
        
        return papers
    
    def update_impact_factor(self, journal_name: str, impact_factor: float) -> bool:
        """
        手动更新或添加期刊影响因子
        
        Args:
            journal_name: 期刊名称
            impact_factor: 影响因子值
            
        Returns:
            是否成功更新
        """
        try:
            journal_lower = journal_name.lower().strip()
            self.common_journals[journal_lower] = impact_factor
            self.cache[journal_lower] = impact_factor
            self._save_cache()
            print(f"Updated impact factor for '{journal_name}': {impact_factor}")
            return True
        except Exception as e:
            print(f"Error updating impact factor: {e}")
            return False
    
    def get_stats(self) -> Dict:
        """获取影响因子数据库统计信息"""
        return {
            'total_journals_in_db': len(self.common_journals),
            'cached_journals': len(self.cache),
            'db_sample': list(self.common_journals.keys())[:10]
        }
